SELECT
    COUNTY_NUMBER,
    CONDITION,
    COUNT(*) AS CONDITION_COUNT,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS LAST_UPDATED
FROM {{ ref('road_conditions_silver') }}
GROUP BY
    COUNTY_NUMBER,
    CONDITION